### PR TITLE
new baseline images for new imageMagick converter

### PR DESCRIPTION
**Pull request by pineapplespatula**

### CODE REVIEW

**Comment by mcilroyc** [comment]
This looks solid to me.  Assigning @chadrolfs to double check too.
Two specific notes:

- png8.png looks way better AND is a smaller file size
- the mauti.webp file did grow in size (286666 -> 310608 bytes) but otherwise looks the same to my eye.

**Comment by pineapplespatula** [comment]
one note, this may raise the bar on our decision to make the switch to FLite by default.

**Comment by chadrolfs** [comment]
Yes - png8.png is much better and smaller in file size. 
gif.gif, however, has slight quality degradation that is noticeable to the naked eye.  It's file size is smaller too.

**Comment by mcilroyc** [comment]
That is concerning that the gif is noticeably worse.  I looked at the IM changelog and didn't notice anything obvious that would affect it.    Also, doing a comparison of GIFs produced by the two versions of `convert` using *no options* on the command line, there doesn't seem to be any noticeable difference.  Maybe something has changed with the way our options (via generator) are being interpreted.  Thoughts @pineapplespatula ?

**Comment by pineapplespatula** [comment]
We are using these arguments :
( -clone 0 ) -delete 0 ( -clone 0 -background #fff -flatten -clone 0 -channel A -threshold 99% -compose dst-in -composite ) -delete 0

with this comment
            // Make it so that pixels that were <1% transparent before become fully transparent
            // while the other pixels have the same color as if seen against a white background
            // Create a copy of the original image, making it truly RGBA, and delete the ARGB original
            // Copy the image and flatten it, then apply the binary transparency of another copy
            // Afterwards, remove the RGBA image as well, leaving just one image

I would vote for logging a bug on the regression and revisiting it after 17.0

**Comment by mcilroyc** [comment]
merging....

**Pull request merged**
