### PR TITLE
replace imagemagick produced results with flite produced results

### PR DESCRIPTION
**Pull request by pineapplespatula**
I'm not sure how to verify such a wide spread change. @mcilroyc  @chadrolfs  do you have any ideas?

### CODE REVIEW

**Comment by pineapplespatula** [comment]
A1-A50, and rectangle 1-50 have a zero comparison between master and the new files when you remove flatten from the conversion call. ( which means they are pixel for pixel the same before flattening with the image magick background field )

**Comment by pineapplespatula** [comment]
```16bit-dither/16bit-dither-assets/generator-export.png 
3D-layer/3D-in-Artboard-assets/Andy.jpg 
adjustment-layer-1/adjustment-layer-1-assets/bar.png 
adjustment-layer-1/adjustment-layer-1-assets/foo.png 
adjustment-layer-2/adjustment-layer-2-assets/dot1.png 
adjustment-layer-2/adjustment-layer-2-assets/dot1andrect.png 
adjustment-layer-2/adjustment-layer-2-assets/dot1group.png 
adjustment-layer-2/adjustment-layer-2-assets/hiddendot.png 
adjustment-layer-3/adjustment-layer-3-assets/dot1.png 
adjustment-layer-3/adjustment-layer-3-assets/dot1andrect.png 
adjustment-layer-3/adjustment-layer-3-assets/dot1group.png 
adjustment-layer-3/adjustment-layer-3-assets/hiddendot.png 
all-file-types/alltypes-assets/jpeg1.jpg 
all-file-types/alltypes-assets/jpeg100.jpg 
all-file-types/alltypes-assets/jpeg50.jpg 
all-file-types/alltypes-assets/png.png 
all-file-types/alltypes-assets/png32.png 
all-file-types/alltypes-assets/png8.png 
artboards/artboards-assets/artboard.jpg 
artboards/artboards-assets/artboard_small:.png 
artboards-2/artboards-2-assets/bulb-outside-artboard.png 
artboards-2/artboards-2-assets/Group-3rdChild.jpg 
artboards-2/artboards-2-assets/GroupOutsideAB.png 
artboards-2/artboards-2-assets/nested-outside-artboard.png 
artboards-2/artboards-2-assets/nested-rect.jpg 
assets-issue-244/deepbounds-assets/Group 2.png 
clipping/clipping-assets/left.jpg 
color-space-conversion-default/prophoto-color-space-assets/ellipse2.png 
color-space-conversion-off/prophoto-color-space-assets/ellipse2.png 
color-space-conversion-on/prophoto-color-space-assets/ellipse2.png 
complex-vector-mask/icon-redStar-assets/red-star.png 
default-test/default-test-assets/hi/vertical@2x.png 
default-test/default-test-assets/lo/vertical.png 
goodbye-world/goodbye-assets/bye/bye.png 
goodbye-world/goodbye-assets/hi.png 
hello-world/hello-world-assets/hi.png 
hidden_layer/hidden_layer_with_drop_shadow-assets/hidden_layer.png 
layer-comps/layer-comps-assets/Rectangle 1.png 
masks/masks-assets/2.png 
masks/masks-assets/2@2x.png 
masks/masks-assets/3.png 
masks/masks-assets/3@2x.png 
masks/masks-assets/4.png 
masks/masks-assets/4@2x.png 
masks/masks-assets/5@2x.png 
png24a/png24a-assets/solid-png24.png 
png24a/png24a-assets/transparent-png24a.png 
png24a/png24a-assets/transparent-png32.png 
png8-convert/png8-convert-assets/png32.png 
png8-convert/png8-convert-assets/png8.png 
png8-pngquant/png8-pngquant-assets/png32.png 
png8-pngquant/png8-pngquant-assets/png8.png 
resize-with-effects/resizeeffects-assets/background-double.png 
resize-with-effects/resizeeffects-assets/background-half.png 
resize-with-effects/resizeeffects-assets/background-third.png 
scaled-layer-effects/scaled-layer-effects-assets/glow100.png 
scaled-layer-effects/scaled-layer-effects-assets/glow150.png 
scaled-layer-effects/scaled-layer-effects-assets/glow200.png 
scaled-layer-effects/scaled-layer-effects-assets/glow33.png 
scaled-layer-effects/scaled-layer-effects-assets/glow333.png 
scaled-layer-effects/scaled-layer-effects-assets/glow50.png 
smart-object-resize/smart-object-resize-assets/background-double.png 
smart-object-resize/smart-object-resize-assets/background-half.png 
smart-object-resize/smart-object-resize-assets/background-third.png 
smart-object-resize-2/smart-object-resize-2-assets/10000raster.png 
```

**Comment by pineapplespatula** [comment]
I pasted above a list of the 65 files that have some pixel level differences between flite and imagemagick

**Comment by pineapplespatula** [comment]
@chadrolfs  I've looked at a sample of the 65 image files, and i dont seem many differences. I dont currently have any good ideas as to how to winnow the list further though

**Comment by pineapplespatula** [comment]
requires https://github.com/adobe-photoshop/generator-assets/pull/421

**Comment by chadrolfs** [comment]
running this with the new genr jenkins build (on Mac, still waiting for Win to finish building), I get 2 failures:

screen shot 2016-11-01 at 2 42 12 pm

**Comment by chadrolfs** [comment]
I'm not sure how to proceed with this.  There seems to be different results in the failures between build 358 and 359.  No idea why?

358:
```failed: wildcards - 2 error(s)
   file height-wildcard.png has a comparison metric of 10.5834 > 10
   file width-wildcard.png has a comparison metric of 10.5834 > 10```

359:
```failed: wildcards - 2 error(s)
   file height-wildcard.png has a comparison metric of 17.1992 > 10
   file width-wildcard.png has a comparison metric of 17.1992 > 10```

**Comment by pineapplespatula** [comment]
I also cant figure out what the difference is. they seem like identical files to me.. digging a little more

**Comment by chadrolfs** [comment]
similar results/failures as above.  New metric is different from the first two.  This is with build 361:
g-a-a-genr361mac-fliteon

**Comment by chadrolfs** [comment]
so comparing the 2 output asset files for the wildcard test (master vs. flite branch), I think I see the difference.
besides the slight file size (13 bytes),
master output file has a color profile attached sRGB IEC61966-2.1 and Alpha channel: No
whereas flite asset files do not have a color profile attached and Alpha channel: Yes

**Pull request merged**
