### PR TITLE
More Artboards tests

### PR DESCRIPTION
**Pull request by chadrolfs**
tests export of: 
- different artboard background options
- shape layers that are outside artboards
- png/jpg/gif/svg formats
- visible and non-visible adjustment layers
- nested group/layer

### CODE REVIEW

**Comment by pineapplespatula** [comment]
i got some errors 
failed: artboards-2 - 6 error(s)
   file Group-3rdChild.gif is unexpectedly in output
   file Group-3rdChild.jpg is unexpectedly in output
   file Group-3rdChild.png is unexpectedly in output
   file nested-rect.gif has a comparison metric of 29841.7 > 10
   file nested-rect.jpg has a comparison metric of 29839.1 > 10
   file nested-rect.png has a comparison metric of 29841.7 > 10

**Comment by chadrolfs** [comment]
doh!  forgot to update the assets after some changes to visibility of adjustment layer, etc. 
just pushed updated/correct assets.

btw, I noticed layers that are exported as svg don't assume adjustment layer application.  Bug or as designed? (compare all the nested-rect.type assets, all have the adjustment layer applied except for svg)

**Comment by chadrolfs** [comment]
@pineapplespatula this should be good to go now.  Can you take a look and merge if all looks well to you?

**Comment by pineapplespatula** [comment]
I'm still getting failures failed: artboards-2 - 3 error(s)
   file nested-rect.png has a comparison metric of 29841.7 > 10
   file nested-rect.jpg has a comparison metric of 29839.1 > 10
   file nested-rect.gif has a comparison metric of 29841.7 > 10

**Comment by chadrolfs** [comment]
Try with 17.0.1 release build.  I'm seeing everything pass on r.106 which includes the bugs we shipped 17.0 with (nesting and color profile).

**Comment by pineapplespatula** [comment]
works for me on the generator jenkins build .

**Pull request merged**
