### PR TITLE
add test for complex vector masks

### PR DESCRIPTION
**Pull request by pineapplespatula**
to prevent regressing bug https://github.com/adobe-photoshop/generator-assets/issues/399

### CODE REVIEW

**Comment by mcilroyc** [comment]
Seems fine to me.  Assigning to @chadrolfs for his critical eye.

Note for the future... This seems like a test case that could be added to an existing test file in order to reduce the overall churn within g-a-a.  Just a thought.

**Comment by chadrolfs** [comment]
I know it's nit picky but I'm not sure this should be called a complex vector mask.  It's really just two shapes combined on one layer with one set to Subtract.  By UI definition there's no vector mask applied here but it's a good test case.  Could we rename the test or, as Cory suggested, maybe just add it to an existing test?

**Comment by pineapplespatula** [comment]
Shape layers are just fill layers with vector masks applied to them. So there is a vector mask. If you have a proposed name that you prefer let me know, but I think it is correct as is.

**Comment by chadrolfs** [comment]
Ah, thanks for the explanation.  Merging...

**Pull request merged**
